env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - warn
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: false
  react/display-name: 2
  react/forbid-prop-types: 0
  react/jsx-closing-bracket-location: 1
  react/jsx-curly-spacing: 1
  react/jsx-boolean-value: 1
  react/jsx-indent:
    - error
    - 2
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-max-props-per-line: 0
  react/jsx-no-duplicate-props: 1
  react/jsx-no-literals: 0
  react/jsx-no-undef: 1
  react/sort-prop-types: 1
  react/sort-props: 0
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/no-danger: 1
  react/no-did-mount-set-state: 1
  react/no-did-update-set-state: 1
  react/no-direct-mutation-state: 1
  react/no-multi-comp: 1
  react/no-set-state: 0
  react/no-unknown-property: 1
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  react/self-closing-comp: 1
  react/sort-comp: 1
